const state={company:null,health:null,dashboard:null,products:[],decisions:[],tools:[],knowledgeDocuments:[],knowledgeMatches:[],evaluationSummary:null,evaluations:[],compare:new Set(),editingId:null,editingRawPayload:{},decisionProductId:null,decisionAction:null,agentSessionId:null,currentView:'overview'};
const pageNames={overview:'经营总览',opportunities:'机会雷达',products:'候选商品',compare:'对比中心',reviews:'审核中心',copilot:'AI 决策室',data:'数据资产',governance:'治理中心'};
const headers={'Content-Type':'application/json'};
const dimensionNames={identity:'商品身份',demand:'需求证据',profit:'利润口径',competition:'竞争证据',compliance:'合规审核'};
const lifecycleNames={candidate:'候选',ready_to_list:'待上架',listed:'已上架',paused:'暂停',abandoned:'已放弃'};
const decisionNames={approved:'已批准',rejected:'已驳回',needs_more_data:'待补数',unsubmitted:'未提交',pending:'待审核'};
const riskNames={high:'高风险',medium:'中风险',low:'低风险',not_analyzed:'未分析'};
const toolBusinessNames={filter_products:'筛选企业商品库',search_products:'检索企业商品库',get_product:'读取商品主档与证据',compare_products:'建立商品决策对比',calculate_profit:'分析利润模型',get_sales_trend:'核验销量趋势',get_price_trend:'核验价格趋势',analyze_competition:'分析竞争情况',simulate_price_change:'执行价格情景模拟',find_historical_failures:'查询企业失败案例',search_company_memory:'检索企业历史记忆',search_company_knowledge:'检索企业知识库',rank_products:'生成候选优先级'};
const gradients=['linear-gradient(135deg,#74cdb1,#168665)','linear-gradient(135deg,#7eb5f7,#4d70d8)','linear-gradient(135deg,#b09af3,#7558d9)','linear-gradient(135deg,#f4bb73,#d27c25)','linear-gradient(135deg,#ef9291,#c94f57)','linear-gradient(135deg,#69ced0,#178f95)'];

async function api(path,opt={}){
  const response=await fetch('/api/v1'+path,{...opt,headers:{...(opt.body instanceof FormData?{}:headers),...(opt.headers||{})}});
  let payload={};try{payload=await response.json()}catch(_){throw new Error('后端返回了无法识别的响应。')}
  if(!response.ok||!payload.success){const detail=payload.detail||payload.error||{};const error=new Error(detail.message||'请求失败');error.code=detail.code;error.detail=detail;throw error}
  return payload.data;
}
function $(selector){return document.querySelector(selector)}
function esc(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]))}
function clean(value){return String(value??'').replace(/[\u0000-\u001f]/g,' ').replace(/[\*`#]/g,'').replace(/\|+/g,' · ').replace(/\s{2,}/g,' ').trim()}
function money(value){return Number.isFinite(Number(value))?Math.round(Number(value)).toLocaleString('zh-CN')+' ₽':'—'}
function percent(value,digits=1){return Number.isFinite(Number(value))?(Number(value)*100).toFixed(digits)+'%':'—'}
function score(value){return Number.isFinite(Number(value))?Number(value).toFixed(1):'—'}
function initial(product){return (product.title||product.brand||'候').trim().slice(0,1)}
function gradient(product){let hash=0;for(const char of String(product.id||product.title||''))hash=(hash*31+char.charCodeAt(0))>>>0;return gradients[hash%gradients.length]}
function apiDate(value){if(!value)return new Date();const raw=String(value);return new Date(/[zZ]$|[+-]\d\d:\d\d$/.test(raw)?raw:raw+'Z')}
function relativeTime(value){if(!value)return '刚刚';const date=apiDate(value),diff=Math.max(0,Date.now()-date.getTime()),minute=60000,hour=3600000,day=86400000;if(diff<minute)return '刚刚';if(diff<hour)return Math.floor(diff/minute)+' 分钟前';if(diff<day)return Math.floor(diff/hour)+' 小时前';return date.toLocaleDateString('zh-CN',{month:'numeric',day:'numeric'})}
function toast(message,error=false){const node=$('#toast');node.textContent=message;node.className='toast show'+(error?' error':'');clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.className='toast',3200)}
function safeUrl(value){try{const url=new URL(String(value||''),location.origin);return ['http:','https:'].includes(url.protocol)?url.href:''}catch(_){return ''}}
function thumb(product,size='mini'){const image=safeUrl(product.main_image_url||product.image_url),klass=size==='large'?'product-thumb':'mini-thumb';return `<div class="${klass}" style="--thumb:${gradient(product)}">${image?`<img src="${esc(image)}" alt="${esc(product.title||'商品图片')}" loading="lazy" referrerpolicy="no-referrer" onerror="this.hidden=true">`:''}<span>${esc(initial(product))}</span></div>`}
function riskBadge(level){return `<span class="risk-badge ${esc(level||'not_analyzed')}">${esc(riskNames[level]||'未分析')}</span>`}
function statusBadge(status,label){return `<span class="status-badge ${esc(status||'candidate')}">${esc(label||lifecycleNames[status]||decisionNames[status]||status)}</span>`}
function progress(value,color='var(--green)'){const safe=Math.max(0,Math.min(100,Number(value)||0));return `<div class="progress-bar"><i style="width:${safe}%;--bar-color:${color}"></i></div>`}

function navigate(view,push=true){
  if(!pageNames[view])view='overview';state.currentView=view;
  document.querySelectorAll('.view').forEach(node=>node.classList.toggle('active',node.id===`view-${view}`));
  document.querySelectorAll('.nav-item').forEach(node=>node.classList.toggle('active',node.dataset.view===view));
  $('#currentPageName').textContent=pageNames[view];
  if(push&&location.hash!==`#${view}`)history.pushState(null,'',`#${view}`);
  toggleSidebar(false);window.scrollTo({top:0,behavior:'smooth'});
  if(view==='compare')renderCompare();if(view==='products')renderProducts();if(view==='reviews')renderReviews();if(view==='data')refreshKnowledge();if(view==='governance')refreshEvaluations();
}
function toggleSidebar(open){$('#sidebar').classList.toggle('open',open)}
function globalSearch(event){if(event.key==='Enter'){const value=event.currentTarget.value.trim();navigate('products');$('#productSearch').value=value;renderProducts()}}
function focusAgent(){setTimeout(()=>$('#agentQuery')?.focus(),120)}
window.addEventListener('hashchange',()=>navigate(location.hash.slice(1)||'overview',false));
document.addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();if(state.currentView==='copilot')focusAgent();else $('#globalSearch')?.focus()}if(event.key==='Escape'){closeDrawer();closeEditor();closeDecisionModal()}});

async function refreshAll(){
  const results=await Promise.allSettled([api('/companies/me'),api('/health'),api('/dashboard/overview'),api('/products'),api('/decisions'),api('/agent/tools')]);
  if(results[0].status==='fulfilled')state.company=results[0].value;
  if(results[1].status==='fulfilled')state.health=results[1].value;
  if(results[2].status==='fulfilled')state.dashboard=results[2].value;
  if(results[3].status==='fulfilled')state.products=results[3].value;
  if(results[4].status==='fulfilled')state.decisions=results[4].value;
  if(results[5].status==='fulfilled')state.tools=results[5].value;
  const failure=results.find(item=>item.status==='rejected');if(failure)toast(failure.reason.message,true);
  renderAll();
}
function renderAll(){renderShell();renderOverview();renderOpportunities();renderProducts();renderCompare();renderReviews();renderData();renderGovernance();renderCopilotSide()}
function renderShell(){
  const metrics=state.dashboard?.metrics||{};
  $('#sideProductCount').textContent=metrics.total_products||0;$('#sideCompareCount').textContent=state.compare.size;
  $('#sideReviewCount').textContent=metrics.pending_reviews||0;$('#notificationCount').textContent=metrics.high_risk_products||0;
  $('#profileCompany').textContent=state.company?.name||'中贸通选品团队';$('#profileRole').textContent=roleName(state.company?.role);
  const agent=state.dashboard?.agent||{},configured=state.health?.llm_configured;$('#sideAgentStatus').textContent=agent.status==='error'?'智谱验证失败 · 已安全回退':agent.status==='ready'?`智谱 ${agent.model||''} · 已验证`:configured?`智谱 ${agent.model||''} · 待首次验证`:'确定性回退 · 未连接模型';
}
function roleName(role){return ({company_admin:'企业管理员',super_admin:'超级管理员',reviewer:'审核员',analyst:'分析师',operator:'运营员',viewer:'只读访客'})[role]||role||'本地角色'}

function renderOverview(){
  const d=state.dashboard||{metrics:{},pipeline:[],categories:[],recent_activity:[],review_queue:[],agent:{}};const m=d.metrics||{};
  $('#emptyPortfolio').classList.toggle('hidden',!d.is_demo_empty);
  const cards=[
    ['候选商品',m.total_products||0,'个','本周企业候选池','#0f8f68','#e5f7f0','box'],
    ['平均动态推荐度',m.average_score??'—','分',m.analyzed_products?`${m.analyzed_products} 个已分析`:'等待分析','#3978f6','#eaf1ff','score'],
    ['已验证月利润潜力',m.verified_monthly_profit_potential?money(m.verified_monthly_profit_potential):'—','', '只计算有销量证据的商品','#7558e8','#eeeafe','profit'],
    ['待人工审核',m.pending_reviews||0,'项',`${m.high_risk_products||0} 个高风险优先`,'#d98120','#fff2df','review']
  ];
  $('#overviewMetrics').innerHTML=cards.map((item,index)=>`<article class="metric-card panel" style="--metric-color:${item[4]};--metric-soft:${item[5]}"><div class="metric-top"><span>${item[0]}</span><div class="metric-icon">${['◆','↗','₽','✓'][index]}</div></div><strong>${esc(item[1])}${item[2]?`<small style="font-size:10px;margin-left:3px">${item[2]}</small>`:''}</strong><div class="metric-foot"><b>${index===1&&m.average_score!=null?'可信评分':''}</b><span>${item[3]}</span></div></article>`).join('');
  renderMatrix();renderDailyBrief();renderPipeline();renderCategories();renderActivity();
}
function renderMatrix(){
  const items=state.products.filter(item=>item.analysis);let html='<div class="matrix-zone high">高利润 · 高推荐</div><div class="matrix-zone watch">低信号 · 待研究</div>';
  if(!items.length){html+='<div class="matrix-empty">分析商品后，机会组合会显示在这里</div>';$('#portfolioMatrix').innerHTML=html;return}
  html+=items.map(item=>{const a=item.analysis||{},x=Math.max(4,Math.min(96,Number(a.recommendation_score)||0)),margin=Math.max(-.1,Math.min(.6,Number(item.current_margin_rate)||0)),y=Math.max(5,Math.min(95,(margin+.1)/.7*100)),size=Math.max(26,Math.min(52,25+Math.sqrt(Number(item.latest_30d_sales)||0)*1.2)),color=a.risk_level==='high'?'#df665d':a.risk_level==='medium'?'#dc943d':'#1da77e';return `<button class="matrix-dot" style="left:${x}%;bottom:${y}%;--size:${size}px;--dot:${color}" onclick="viewProduct('${item.id}')" title="${esc(item.title)}"><span>${Math.round(x)}</span><label>${esc(item.title.slice(0,9))}</label></button>`}).join('');$('#portfolioMatrix').innerHTML=html;
}
function renderDailyBrief(){
  const d=state.dashboard||{},m=d.metrics||{},top=[...state.products].filter(p=>p.analysis).sort((a,b)=>(b.analysis.recommendation_score||0)-(a.analysis.recommendation_score||0))[0];
  $('#briefModel').textContent=d.agent?.status==='error'?'确定性回退 · 模型验证失败':d.agent?.configured?`${d.agent.model} · Tool Calling`:'确定性决策引擎';
  if(!state.products.length){$('#dailyBrief').innerHTML='<p class="brief-lead">候选池尚未建立，先导入或创建商品，才能生成基于证据的经营简报。</p><div class="brief-list"><div><i>01</i> 从浏览器扩展同步当前可见商品</div><div><i>02</i> 补齐企业成本、销量与合规证据</div></div>';return}
  $('#dailyBrief').innerHTML=`<p class="brief-lead">当前有 <b>${m.pending_reviews||0}</b> 个候选等待人工处理${top?`，<b>${esc(top.title)}</b> 的动态推荐度最高（${score(top.analysis.recommendation_score)}）`:''}。</p><div class="brief-list"><div><i>01</i><span>${m.high_risk_products||0} 个高风险商品应优先处理合规或证据缺口。</span></div><div><i>02</i><span>已验证月利润潜力约 ${money(m.verified_monthly_profit_potential||0)}，未提供销量证据的商品未计入。</span></div><div><i>03</i><span>批准进入仍需分析、证据与合规三道闸门全部通过。</span></div></div>`;
}
function renderPipeline(){const counts=Object.fromEntries((state.dashboard?.pipeline||[]).map(x=>[x.status,x.count]));const rows=[['candidate','候选池'],['ready_to_list','待上架'],['listed','已上架'],['abandoned','已放弃']],max=Math.max(1,...rows.map(x=>counts[x[0]]||0));$('#pipelineChart').innerHTML=rows.map(([key,label])=>`<div class="pipeline-step"><div class="pipeline-bar" style="--h:${Math.max(12,(counts[key]||0)/max*125)}px"></div><b>${counts[key]||0}</b><span>${label}</span></div>`).join('')}
function renderCategories(){const rows=state.dashboard?.categories||[];$('#categoryRanking').innerHTML=rows.length?rows.slice(0,5).map((item,index)=>`<div class="ranking-row"><div class="ranking-index">${index+1}</div><div class="ranking-info"><b>${esc(item.name)}</b><div class="rank-bar"><i style="width:${Math.max(4,item.average_score)}%"></i></div></div><span>${score(item.average_score)}</span></div>`).join(''):'<div class="muted" style="font-size:10px;padding:35px 0;text-align:center">暂无类目信号</div>'}
function renderActivity(){const rows=state.dashboard?.recent_activity||[];$('#activityFeed').innerHTML=rows.length?rows.slice(0,6).map(item=>`<div class="activity-item"><div class="activity-icon ${item.type==='agent'?'agent':''}">${item.type==='agent'?'AI':'品'}</div><div><b>${esc(item.title)}</b><p>${esc(item.detail)}</p></div><time>${relativeTime(item.created_at)}</time></div>`).join(''):'<div class="muted" style="font-size:10px;padding:35px 0;text-align:center">暂无活动记录</div>'}

function renderOpportunities(){
  const items=[...state.products].sort((a,b)=>((b.analysis?.recommendation_score)||0)-((a.analysis?.recommendation_score)||0));
  $('#opportunityCards').innerHTML=items.length?items.map(item=>{const a=item.analysis||{};return `<article class="opportunity-card">${thumb(item,'large')}<h3>${esc(item.title)}</h3><p>${esc(item.category_path||'类目待确认')}</p><div class="signal-row"><div><span>30天销量</span><b>${item.latest_30d_sales||'—'}</b></div><div><span>净利率</span><b>${item.procurement_cost>0?percent(item.current_margin_rate):'—'}</b></div><div><span>竞品数</span><b>${item.competitor_count||'—'}</b></div></div><div class="card-foot"><span class="score-chip">机会分 ${score(a.recommendation_score)}</span><button onclick="viewProduct('${item.id}')">查看证据 →</button></div></article>`}).join(''):'<div class="panel" style="grid-column:1/-1;text-align:center;padding:60px;color:#7c8781;font-size:11px">候选池为空，暂时没有可计算的企业机会信号。</div>';
  renderCoverageRadar();
}
function renderCoverageRadar(){const rows=state.dashboard?.data_coverage||[],avg=rows.length?Math.round(rows.reduce((sum,x)=>sum+x.percent,0)/rows.length):0;$('#coverageRadar').innerHTML=`<div class="coverage-ring" style="--coverage:${avg}%"><div><b>${avg}%</b><span>综合证据覆盖</span></div></div>`+rows.map((item,index)=>`<div class="coverage-item"><span>${dimensionNames[item.key]||item.key}</span><div class="bar"><i style="width:${item.percent}%;--bar-color:${['#11a77a','#3c83ed','#7760db','#d58b2f','#1da393'][index]}"></i></div><b>${item.percent}%</b></div>`).join('')}
function setOpportunity(value){$('#opportunityQuery').value=value;$('#opportunityQuery').focus()}
function opportunityAsk(){const value=$('#opportunityQuery').value.trim();if(!value){toast('请先描述你的市场目标。',true);return}navigate('copilot');setPrompt(`请基于当前企业候选池研究这个机会方向：${value}。先说明已有证据，再列出缺失数据和下一步研究计划。`)}

function filteredProducts(){const q=($('#productSearch')?.value||'').trim().toLowerCase(),status=$('#statusFilter')?.value||'all',risk=$('#riskFilter')?.value||'all';return state.products.filter(item=>(!q||[item.title,item.brand,item.category_path,item.external_product_id].join(' ').toLowerCase().includes(q))&&(status==='all'||item.lifecycle_status===status)&&(risk==='all'||item.analysis?.risk_level===risk))}
function renderProducts(){
  const rows=filteredProducts();if($('#productResultCount'))$('#productResultCount').textContent=`显示 ${rows.length} / ${state.products.length} 个候选`;
  if(!$('#productRows'))return;
  $('#productRows').innerHTML=rows.length?rows.map(item=>{const a=item.analysis||{},growth=Number(item.sales_growth_rate)||0,complete=a.evidence_completeness?.percent||0,selected=state.compare.has(item.id);return `<tr><td class="check-col"><input class="compare-check" type="checkbox" ${selected?'checked':''} onchange="toggleCompare('${item.id}',this.checked)" title="加入对比"></td><td><div class="product-cell">${thumb(item)}<div><b>${esc(item.title)}</b><span>${esc(item.brand||'品牌待确认')} · ${esc((item.category_path||'类目待确认').split('>').slice(-1)[0].trim())}</span></div></div></td><td><div class="money-main">${money(item.current_price)}</div><div class="money-sub">净利率 ${item.procurement_cost>0?percent(item.current_margin_rate):'待补成本'}</div></td><td><b>${item.latest_30d_sales||'—'}</b><div class="demand-sub ${growth>=0?'up':'down'}">${growth?`${growth>0?'↑':'↓'} ${Math.abs(growth).toFixed(1)}%`:'无趋势证据'}</div></td><td><div class="score-stack"><span class="score-number">${score(a.recommendation_score)}</span><div class="score-bars" title="需求 / 利润 / 竞争 / 合规"><i style="--score:${a.demand_score||0}%;--color:#3d82ed"></i><i style="--score:${a.profit_score||0}%;--color:#14a478"></i><i style="--score:${a.competition_score||0}%;--color:#dd9135"></i><i style="--score:${a.compliance_score||0}%;--color:#7b62dd"></i></div></div></td><td><div class="completeness"><div><span>${a.evidence_completeness?.grade==='complete'?'完整':'待补数'}</span><b>${complete}%</b></div>${progress(complete)}</div></td><td><div>${riskBadge(a.risk_level)}</div><div style="margin-top:5px">${statusBadge(item.lifecycle_status)}</div></td><td><div class="row-actions"><button onclick="viewProduct('${item.id}')">查看</button><button onclick="editProduct('${item.id}')">编辑</button></div></td></tr>`}).join(''):'<tr><td colspan="8" class="empty-row">没有符合筛选条件的候选商品。</td></tr>';
}
function toggleCompare(id,checked){if(checked&&state.compare.size>=4){toast('对比中心最多选择 4 个商品。',true);renderProducts();return}checked?state.compare.add(id):state.compare.delete(id);renderShell();renderCompare()}
function clearCompare(){state.compare.clear();renderShell();renderProducts();renderCompare()}
function renderCompare(){
  const items=state.products.filter(item=>state.compare.has(item.id));const ready=items.length>=2;
  $('#compareEmpty')?.classList.toggle('hidden',ready);$('#compareWorkspace')?.classList.toggle('hidden',!ready);if(!ready)return;
  $('#compareCards').innerHTML=items.map(item=>`<article class="compare-card"><button class="compare-remove" onclick="toggleCompare('${item.id}',false)">×</button>${thumb(item,'large')}<h3>${esc(item.title)}</h3><p>${esc(item.brand||'品牌待确认')} · ${money(item.current_price)}</p></article>`).join('');
  const definitions=[
    ['当前售价',item=>item.current_price,'money','min'],['当前净利率',item=>item.procurement_cost>0?item.current_margin_rate:null,'percent','max'],['近30天销量',item=>item.latest_30d_sales||null,'number','max'],['销量环比',item=>item.sales_growth_rate||null,'percentRaw','max'],['竞品数量',item=>item.competitor_count||null,'number','min'],['需求分',item=>item.analysis?.demand_score,'score','max'],['利润分',item=>item.analysis?.profit_score,'score','max'],['竞争分',item=>item.analysis?.competition_score,'score','max'],['合规分',item=>item.analysis?.compliance_score,'score','max'],['动态推荐度',item=>item.analysis?.recommendation_score,'score','max'],['证据完整度',item=>item.analysis?.evidence_completeness?.percent,'percentWhole','max'],['合规状态',item=>item.compliance_status,'status',null]
  ];
  const format=(value,type)=>value==null?'—':type==='money'?money(value):type==='percent'?percent(value):type==='percentRaw'?`${Number(value).toFixed(1)}%`:type==='percentWhole'?`${value}%`:type==='score'?score(value):type==='status'?({approved:'通过',pending:'待核验',rejected:'未通过'}[value]||value):value;
  $('#comparisonTable').innerHTML=`<thead><tr><th>比较维度</th>${items.map(item=>`<th>${esc(item.title)}</th>`).join('')}</tr></thead><tbody>`+definitions.map(([label,getter,type,best])=>{const values=items.map(getter),numeric=values.filter(x=>typeof x==='number'),bestValue=best&&numeric.length?(best==='max'?Math.max(...numeric):Math.min(...numeric)):null;return `<tr><td>${label}</td>${values.map(value=>{const isBest=bestValue!=null&&value===bestValue,isBlocked=label==='合规状态'&&value==='rejected';return `<td class="${isBest?'best-cell ':''}${isBlocked?'blocked-cell':''}">${esc(format(value,type))}</td>`}).join('')}</tr>`}).join('')+'</tbody>';
}
function askCompare(){const items=state.products.filter(item=>state.compare.has(item.id));if(items.length<2)return;navigate('copilot');setPrompt(`请比较以下候选商品：${items.map(x=>x.title).join('、')}。重点说明各自利润、需求、竞争、合规和数据缺口，并给出人工审核顺序。`)}

function renderReviews(){
  const rows=state.decisions||[],counts={approved:0,rejected:0,needs_more_data:0,unsubmitted:0};rows.forEach(row=>counts[row.decision?.status||'unsubmitted']=(counts[row.decision?.status||'unsubmitted']||0)+1);
  $('#reviewSummary').innerHTML=[['待处理',(counts.unsubmitted||0)+(counts.needs_more_data||0)],['可批准',rows.filter(x=>x.can_approve&&x.decision?.status!=='approved').length],['已批准',counts.approved||0],['已驳回',counts.rejected||0]].map(([label,value])=>`<div class="summary-chip"><span>${label}</span><b>${value}</b></div>`).join('');
  const priority=row=>['approved','rejected'].includes(row.decision?.status)?3:row.can_approve?0:1;
  const sorted=[...rows].sort((a,b)=>priority(a)-priority(b));
  $('#reviewQueue').innerHTML=sorted.length?sorted.map(row=>{const p=row.product,a=row.analysis||{},status=row.decision?.status||'unsubmitted';const gates=[['分析',row.gates.analysis_complete],['证据',row.gates.evidence_complete],['合规',row.gates.compliance_approved]];return `<article class="review-item"><div class="review-product">${thumb(p)}<div><b>${esc(p.title)}</b><span>${esc(p.brand||'品牌待确认')} · 推荐度 ${score(a.recommendation_score)}</span></div></div><div><div class="gate-list">${gates.map(([name,pass])=>`<span class="gate ${pass?'pass':'fail'}">${pass?'✓':'!'} ${name}</span>`).join('')} ${statusBadge(status,decisionNames[status])}</div>${row.decision?.reason?`<div class="money-sub" style="margin-top:7px">最近原因：${esc(row.decision.reason)}</div>`:''}</div><div class="review-actions"><button onclick="viewProduct('${p.id}')">查看证据</button><button class="primary-mini" onclick="openDecisionModal('${p.id}')">人工审核</button></div></article>`}).join(''):'<div class="muted" style="text-align:center;padding:50px;font-size:10px">候选池为空，暂无审核任务。</div>';
}
function openDecisionModal(id){state.decisionProductId=id;state.decisionAction=null;const row=state.decisions.find(x=>x.product.id===id),p=row?.product||state.products.find(x=>x.id===id),approve=$('.decision-options button[data-action="approve"]');$('#decisionTitle').textContent=`审核：${p?.title||'候选商品'}`;$('#decisionReason').value='';document.querySelectorAll('.decision-options button').forEach(x=>x.classList.remove('selected'));approve.disabled=!row?.can_approve;approve.title=approve.disabled?'分析、证据或合规闸门尚未全部通过。':'全部闸门已通过，可以提交批准。';$('#decisionModal').classList.remove('hidden');document.body.classList.add('no-scroll')}
function closeDecisionModal(){if($('#decisionModal'))$('#decisionModal').classList.add('hidden');state.decisionAction=null;state.decisionProductId=null;if($('#drawer').classList.contains('hidden')&&$('#editor').classList.contains('hidden'))document.body.classList.remove('no-scroll')}
function chooseDecision(action,button){if(button.disabled)return;state.decisionAction=action;document.querySelectorAll('.decision-options button').forEach(x=>x.classList.toggle('selected',x===button));const suggestions={approve:'证据与合规闸门均已通过，同意进入上架准备。',needs_more_data:'关键证据仍不完整，请按缺失项补齐后重新提交。',reject:'当前风险不可接受，驳回并记录为企业历史案例。'};if(!$('#decisionReason').value)$('#decisionReason').value=suggestions[action]}
async function submitDecision(){if(!state.decisionAction){toast('请选择审核结论。',true);return}const reason=$('#decisionReason').value.trim();if(reason.length<2){toast('请填写审核原因。',true);return}const button=$('#decisionSubmit');button.disabled=true;button.textContent='正在提交…';try{await api(`/products/${state.decisionProductId}/decisions`,{method:'POST',body:JSON.stringify({action:state.decisionAction,reason})});closeDecisionModal();toast('审核结论已写入决策记录。');await refreshAll()}catch(error){toast(error.message,true)}finally{button.disabled=false;button.textContent='提交并留痕'}}

function renderData(){
  const m=state.dashboard?.metrics||{},coverage=state.dashboard?.data_coverage||[];
  $('#dataMetrics').innerHTML=[['商品主档',m.total_products||0,'企业范围'],['已分析',m.analyzed_products||0,'生成规则快照'],['证据完整',state.products.filter(x=>x.analysis?.evidence_completeness?.grade==='complete').length,'可进入审核'],['企业记忆','已启用','失败原因可检索']].map(([label,value,note])=>`<article class="metric-card panel"><div class="metric-top"><span>${label}</span></div><strong>${value}</strong><div class="metric-foot"><span>${note}</span></div></article>`).join('');
  const colors=['#11a77a','#3c83ed','#7760db','#d58b2f','#1da393'];$('#dataCoverage').innerHTML=coverage.map((item,index)=>`<div class="coverage-bar-row"><span>${dimensionNames[item.key]||item.key}</span>${progress(item.percent,colors[index])}<b>${item.percent}%</b></div>`).join('')||'<div class="muted">暂无数据</div>';
  const quality=[];state.products.forEach(product=>(product.analysis?.missing_data||[]).forEach(item=>quality.push({product,item})));$('#dataQualityQueue').innerHTML=quality.length?quality.slice(0,12).map(({product,item})=>`<div class="quality-item"><i>!</i><div><b>${esc(product.title)} · ${esc(dimensionNames[item.dimension]||item.dimension)}</b><span>${esc(item.missing)}</span></div><button onclick="editProduct('${product.id}')">补数 →</button></div>`).join(''):'<div class="muted" style="grid-column:1/-1;text-align:center;padding:30px;font-size:10px">当前没有待补数项目。</div>';
}
function renderKnowledge(){const documents=$('#knowledgeDocuments'),matches=$('#knowledgeMatches');if(!documents||!matches)return;documents.innerHTML=state.knowledgeDocuments.length?state.knowledgeDocuments.map(item=>`<article><i>${esc((item.filename.split('.').pop()||'DOC').toUpperCase())}</i><div><b>${esc(item.filename)}</b><span>${item.chunk_count} 个知识片段 · ${relativeTime(item.created_at)}</span></div><em>${esc(item.status==='ready'?'可检索':item.status)}</em></article>`).join(''):'<p class="muted">尚未上传企业资料。</p>';matches.innerHTML=state.knowledgeMatches.length?state.knowledgeMatches.map(item=>`<article><header><b>${esc(item.filename)}</b><em>相关度 ${(Number(item.score)*100).toFixed(0)}%</em></header><p>${esc(clean(item.content).slice(0,360))}${String(item.content||'').length>360?'…':''}</p><span>企业知识库 · ${esc(item.embedding_mode)}</span></article>`).join(''):'<p class="muted">输入问题后显示命中的企业证据片段。</p>'}
async function refreshKnowledge(){try{state.knowledgeDocuments=await api('/knowledge/documents');renderKnowledge()}catch(error){if(state.currentView==='data')toast(`知识库读取失败：${error.message}`,true)}}
async function uploadKnowledge(){const picker=$('#knowledgeFile'),file=picker?.files?.[0],button=$('#knowledgeUploadButton');if(!file){toast('请先选择 CSV、Excel、PDF、TXT 或 Markdown 文件。',true);return}if(file.size>10*1024*1024){toast('文件不能超过 10 MB。',true);return}const data=new FormData();data.append('file',file);button.disabled=true;button.textContent='正在解析并建立索引…';try{const result=await api('/knowledge/documents',{method:'POST',body:data});toast(result.created?`已接入 ${result.document.filename}，生成 ${result.document.chunk_count} 个知识片段。`:`${result.document.filename} 已存在，未重复创建。`);picker.value='';await refreshKnowledge()}catch(error){toast(error.message,true)}finally{button.disabled=false;button.textContent='上传并建立索引'}}
function knowledgeKeydown(event){if(event.key==='Enter'){event.preventDefault();searchKnowledge()}}
async function searchKnowledge(){const query=$('#knowledgeQuery')?.value.trim();if(!query||query.length<2){toast('请输入至少两个字的检索问题。',true);return}try{const result=await api('/knowledge/search',{method:'POST',body:JSON.stringify({query,limit:8})});state.knowledgeMatches=result.matches||[];renderKnowledge();if(!state.knowledgeMatches.length)toast('没有找到相关企业知识，请调整关键词。')}catch(error){toast(error.message,true)}}
function renderGovernance(){
  const agent=state.dashboard?.agent||{},health=state.health||{},isError=agent.status==='error',llmLabel=isError?'验证失败':agent.status==='ready'?'调用正常':agent.configured?'待首次验证':'未配置';$('#governanceStatus').innerHTML=`<article class="system-card ${isError?'error':''}"><i>LLM</i><div><b>智谱模型连接</b><span>${esc(agent.notice||`${agent.model||'未设置'} · ${health.agent_mode||'检查中'}`)}</span></div><em>${llmLabel}</em></article><article class="system-card"><i>RBAC</i><div><b>当前角色权限</b><span>${roleName(state.company?.role)}</span></div><em>后端校验</em></article><article class="system-card warn"><i>HITL</i><div><b>人工审核闸门</b><span>AI 无权直接批准或修改审核状态</span></div><em>强制开启</em></article>`;
  $('#toolCount').textContent=`${state.tools.length} 个工具`;$('#toolRows').innerHTML=state.tools.map(tool=>`<tr><td><div class="tool-name"><b>${esc(tool.name)}</b><span>${esc(tool.description)}</span></div></td><td><code class="permission-code">${esc(tool.permission)}</code></td><td>${riskBadge(tool.risk_level)}</td><td>${tool.timeout_seconds}s</td><td>${tool.idempotent?'是':'否'}</td><td>${statusBadge(tool.allowed?'approved':'rejected',tool.allowed?'允许':'拒绝')}</td></tr>`).join('');
  renderEvaluations();
}
function renderEvaluations(){const summary=state.evaluationSummary||{},metrics=$('#evaluationMetrics'),rows=$('#evaluationRows');if(!metrics||!rows)return;const cards=[['任务完成率',summary.task_success_rate],['回答准确率',summary.answer_accuracy],['工具选择准确率',summary.tool_calling_accuracy],['数据完整度',summary.data_completeness]];metrics.innerHTML=cards.map(([label,value])=>`<div><span>${label}</span><b>${summary.evaluation_count?percent(value):'未运行'}</b></div>`).join('');rows.innerHTML=state.evaluations.length?state.evaluations.slice(0,8).map(item=>`<tr><td>${esc(item.task_name)}</td><td>${statusBadge(item.status==='passed'?'approved':'rejected',item.status==='passed'?'通过':'失败')}</td><td>${percent(item.task_success_rate)}</td><td>${percent(item.answer_accuracy)}</td><td>${percent(item.tool_calling_accuracy)}</td><td>${percent(item.data_completeness)}</td><td>${relativeTime(item.created_at)}</td></tr>`).join(''):'<tr><td colspan="7" class="empty-row">尚未运行本地 Agent 回归评测。</td></tr>'}
async function refreshEvaluations(){try{const [summary,rows]=await Promise.all([api('/evaluations/summary'),api('/evaluations')]);state.evaluationSummary=summary;state.evaluations=rows;renderEvaluations()}catch(error){if(state.currentView==='governance')toast(`评测记录读取失败：${error.message}`,true)}}
async function runEvaluations(){const button=$('#evaluationRunButton');button.disabled=true;button.textContent='正在运行 4 个离线任务…';try{const result=await api('/evaluations/run',{method:'POST',body:'{}'});state.evaluationSummary=result.summary;state.evaluations=[...(result.evaluations||[]),...state.evaluations];renderEvaluations();toast('离线 Agent 回归评测完成，全程未调用 GLM。')}catch(error){toast(error.message,true)}finally{button.disabled=false;button.textContent='运行本地评测'}}
function renderCopilotSide(){const tools=state.tools.filter(x=>x.allowed).slice(0,8);$('#copilotTools').innerHTML=tools.map((tool,index)=>`<div class="tool-mini"><i>${String(index+1).padStart(2,'0')}</i><div><b>${esc(toolBusinessNames[tool.name]||tool.description||tool.name)}</b><span>${esc(tool.description)}</span></div><em>${tool.risk_level}</em></div>`).join('');const m=state.dashboard?.metrics||{},agent=state.dashboard?.agent||{},last=state.lastAgentResult||{};$('#agentContext').innerHTML=`<div class="context-stat"><span>企业候选</span><b>${m.total_products||0} 个</b></div><div class="context-stat"><span>已选对比</span><b>${state.compare.size} 个</b></div><div class="context-stat"><span>待审核</span><b>${m.pending_reviews||0} 项</b></div><div class="context-stat"><span>本次回答来源</span><b>${esc(last.source_badge||'尚未提问')}</b></div><div class="context-stat"><span>本次执行引擎</span><b>${esc(last.active_model||'尚未提问')}</b></div>`}
function setPrompt(text){$('#agentQuery').value=text;focusAgent()}
function agentKeydown(event){if(event.key==='Enter'&&(event.ctrlKey||event.metaKey)){event.preventDefault();askAgent()}}
function insertSelectedProducts(){const items=state.products.filter(x=>state.compare.has(x.id));if(!items.length){toast('请先在候选池勾选商品。',true);return}const current=$('#agentQuery').value.trim();$('#agentQuery').value=(current?current+'\n':'')+`请重点分析：${items.map(x=>x.title).join('、')}。`;focusAgent()}
async function newAgentSession(){try{const session=await api('/agent/sessions',{method:'POST',body:'{}'});state.agentSessionId=session.id;$('#agentOutput').innerHTML='<div class="agent-welcome"><h2>新分析会话已建立</h2><p>上下文将与其他企业和会话隔离。</p></div>';toast('已建立新的分析会话。')}catch(error){toast(error.message,true)}}
function bestProduct(result){return Array.isArray(result.products)&&result.products.length?result.products[0]:null}
function listItems(items,empty){return Array.isArray(items)&&items.length?items.map(item=>`<li>${esc(typeof item==='string'?clean(item):clean(item.missing||item.message||item.action||item.title||JSON.stringify(item)))}</li>`).join(''):`<li>${esc(empty)}</li>`}
function gradeClass(grade){return ['S','A','B','C'].includes(grade)?grade.toLowerCase():'c'}
const agentDecisionNames={RECOMMENDED:'达到推荐标准',REVIEW_REQUIRED:'待人工复核',HUMAN_REVIEW_REQUIRED:'高风险人工复核',NOT_RECOMMENDED:'暂不推荐',INSUFFICIENT_DATA:'证据不足',BLOCKED:'合规阻断'};
function decisionBadge(status){const value=status||'REVIEW_REQUIRED';return `<span class="decision-pill ${value.toLowerCase()}">${esc(agentDecisionNames[value]||value)}</span>`}
function agentProductCard(product,dimensions=[]){
  const url=safeUrl(product.url),dims=new Set(dimensions),profitOnly=dims.has('profit')&&!['demand','competition','compliance','risk','recommendation'].some(x=>dims.has(x)),priceOnly=dims.size===1&&dims.has('price');
  const kpis=priceOnly?`<div><span>当前售价</span><b>${money(product.current_price)}</b></div>`:profitOnly?`<div><span>净利润</span><b>${money(product.net_profit)}</b></div><div><span>净利率</span><b>${percent(product.current_margin_rate)}</b></div><div><span>ROI</span><b>${percent(product.roi)}</b></div>`:`<div><span>推荐度</span><b>${score(product.score)}</b></div><div><span>净利润</span><b>${money(product.net_profit)}</b></div><div><span>净利率</span><b>${percent(product.current_margin_rate)}</b></div><div><span>ROI</span><b>${percent(product.roi)}</b></div>`;
  const bars=priceOnly?'':profitOnly?dimensionRow('利润',product.profit_score,'#11a77a'):`${dimensionRow('利润',product.profit_score,'#11a77a')}${dimensionRow('需求',product.demand_score,'#3c83ed')}${dimensionRow('竞争',product.competition_score,'#d98d30')}${dimensionRow('合规',product.compliance_score,'#15a184')}${dimensionRow('风险安全',product.risk_score,'#775fda')}`;
  const scoped=priceOnly||profitOnly,hardGate=product.decision_status==='BLOCKED'?decisionBadge(product.decision_status):'',grade=scoped?'':`<span class="grade-badge ${gradeClass(product.recommendation_grade)}">${esc(product.recommendation_grade||'C')}</span>`,decision=scoped?hardGate:decisionBadge(product.decision_status),footer=scoped?`${url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">查看来源 ↗</a>`:''}`:`${riskBadge(product.risk_level)}<span>完整度 ${product.completeness}%</span>${url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">查看来源 ↗</a>`:''}`;
  return `<article class="agent-product-card"><div class="agent-product-top">${thumb(product,'large')}${grade}</div>${decision?`<div class="decision-row">${decision}</div>`:''}<h3>${esc(product.title)}</h3><p>${esc(product.brand||'品牌待确认')} · ${esc(product.category_path||'类目待确认')}</p><div class="agent-product-kpis ${priceOnly?'single':''}">${kpis}</div>${bars?`<div class="agent-dimensions">${bars}</div>`:''}<footer>${footer}</footer></article>`;
}
function agentProductTable(products,dimensions=[]){
  if(!products.length)return '';
  const dims=new Set(dimensions),profitOnly=dims.has('profit')&&!['demand','competition','compliance','risk','recommendation'].some(x=>dims.has(x)),priceOnly=dims.size===1&&dims.has('price');
  const hasHardGate=products.some(product=>product.decision_status==='BLOCKED'),gateHead=hasHardGate?'<th>硬性阻断</th>':'';
  const head=priceOnly?'<th>商品</th><th>当前售价</th><th>币种</th><th>来源</th>':profitOnly?`<th>商品</th><th>净利润</th><th>净利率</th><th>ROI</th>${gateHead}<th>来源</th>`:'<th>商品</th><th>等级</th><th>推荐度</th><th>决策状态</th><th>完整度</th><th>风险</th><th>来源</th>';
  const rows=products.map(product=>{const url=safeUrl(product.url),name=`<td><div class="product-cell">${thumb(product)}<div><b>${esc(product.title)}</b><span>${esc(product.external_product_id)}</span></div></div></td>`,source=`<td>${url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">打开 ↗</a>`:'—'}</td>`;if(priceOnly)return `<tr>${name}<td>${money(product.current_price)}</td><td>${esc(product.currency||'RUB')}</td>${source}</tr>`;if(profitOnly)return `<tr>${name}<td>${money(product.net_profit)}</td><td>${percent(product.current_margin_rate)}</td><td>${percent(product.roi)}</td>${hasHardGate?`<td>${product.decision_status==='BLOCKED'?decisionBadge('BLOCKED'):'—'}</td>`:''}${source}</tr>`;return `<tr>${name}<td><span class="grade-badge ${gradeClass(product.recommendation_grade)}">${esc(product.recommendation_grade)}</span></td><td><b>${score(product.score)}</b></td><td>${decisionBadge(product.decision_status)}</td><td>${product.completeness}%</td><td>${riskBadge(product.risk_level)}</td>${source}</tr>`}).join('');
  return `<div class="agent-result-table"><table><thead><tr>${head}</tr></thead><tbody>${rows}</tbody></table></div>`;
}
function agentResultHeader(result,title){const badgeClass=result.response_mode==='glm_success'?'success':result.response_mode==='deterministic_fallback'?'fallback':'rule';return `<div class="answer-title"><div class="ai-avatar"><svg><use href="#i-spark"/></svg></div><div><span class="answer-source ${badgeClass}">${esc(result.source_badge||'规则引擎结果')}</span><h2>${esc(title)}</h2><p>${esc(result.active_model||'确定性 Planner')} · ${result.tool_call_count||0} 次工具调用 · ${result.latency_ms||0} ms</p></div></div>`}
function agentTraceBlock(result){const trace=result.trace||[],timeline=result.tool_trace_summary||[],steps=trace.map(item=>`<li><b>${esc(item.business_label||toolBusinessNames[item.tool]||item.tool)}</b> — ${esc(clean(item.summary))}</li>`).join('')||'<li>暂无执行轨迹。</li>';return `<section class="tool-timeline"><h3>本次 Agent 工作过程</h3>${timeline.length?timeline.map((item,index)=>`<div><i>${String(index+1).padStart(2,'0')}</i><span>${esc(item.replace(/^\d+\.\s*/,''))}</span><b>已完成</b></div>`).join(''):'<p>本次未执行企业工具。</p>'}</section><details class="trace-panel"><summary>查看 ${trace.length} 条可审计执行轨迹</summary><ol>${steps}</ol></details>`}
function renderAgentResult(result){
  const products=result.products||[],dimensions=result.requested_dimensions||[],scope=new Set(result.display_scope||[]),evidence=(result.evidence||[]).map(item=>`${item.title}：${item.summary}`),warnings=result.warnings||result.risks||[],answer=esc(clean(result.answer||result.conclusion||'本次没有返回可用结论。')),type=result.response_type||'decision_report';
  if(type==='simple_fact'){
    const fact=result.fact||{},isPrice=fact.name==='product_price',timestamp=fact.timestamp?apiDate(fact.timestamp).toLocaleString('zh-CN'):'未提供';
    $('#agentOutput').innerHTML=`<div class="agent-answer simple-fact-result">${agentResultHeader(result,'事实查询结果')}<section class="recommendation-hero"><span>直接答案</span><h3>${answer}</h3></section><div class="answer-metrics"><div class="answer-metric"><span>${isPrice?'商品':'事实'}</span><b>${isPrice?esc(products[0]?.title||fact.product_id||'未知'):'企业商品总数'}</b></div><div class="answer-metric"><span>${isPrice?'售价':'数量'}</span><b>${isPrice?`${esc(fact.value)} ${esc(fact.currency||'RUB')}`:esc(fact.value)}</b></div><div class="answer-metric"><span>数据来源</span><b>${esc(fact.source||'企业商品库')}</b></div>${isPrice?`<div class="answer-metric"><span>更新时间</span><b>${esc(timestamp)}</b></div>`:''}</div><div class="provider-boundary">${esc(clean(result.provider_notice||'事实由后端读取并校验。'))}</div></div>`;return;
  }
  if(type==='policy_answer'||type==='clarification'){
    $('#agentOutput').innerHTML=`<div class="agent-answer policy-result">${agentResultHeader(result,type==='policy_answer'?'业务规则答复':'需要补充信息')}<section class="recommendation-hero"><span>${type==='policy_answer'?'规则结论':'澄清问题'}</span><h3>${answer}</h3></section><div class="provider-boundary">${esc(clean(result.provider_notice||'该结论来自后端业务规则，不受页面已选商品影响。'))}</div></div>`;return;
  }
  if(type==='insufficient_data'){
    const suff=result.data_sufficiency||{};
    $('#agentOutput').innerHTML=`<div class="agent-answer insufficient-result">${agentResultHeader(result,'数据充分性核验')}<section class="recommendation-hero"><span>直接答案</span><h3>${answer}</h3></section><div class="answer-metrics"><div class="answer-metric"><span>快照总数</span><b>${suff.snapshot_count??0}</b></div><div class="answer-metric"><span>有效快照</span><b>${suff.valid_sales_snapshot_count??0}</b></div><div class="answer-metric"><span>观察趋势</span><b>${esc(suff.observed_trend||'INSUFFICIENT_DATA')}</b></div><div class="answer-metric"><span>数据状态</span><b>${esc(suff.status||'INSUFFICIENT_DATA')}</b></div></div><div class="answer-grid"><div class="answer-box"><h3>可复核证据</h3><ul>${listItems(evidence,'暂无销量快照证据。')}</ul></div>${warnings.length?`<div class="answer-box"><h3>口径说明</h3><ul>${listItems(warnings,'')}</ul></div>`:''}</div>${scope.has('tool_summary')?agentTraceBlock(result):''}<div class="provider-boundary">${esc(clean(result.provider_notice||'主档报告增速与快照观察趋势分别展示。'))}</div></div>`;return;
  }
  const title=type==='comparison_result'?'商品对比结果':type==='filter_result'?'商品筛选结果':'企业选品决策报告',label=type==='decision_report'?'推荐结论':'直接结果',decision=result.decision_summary||{},topCards=scope.has('products')?products.slice(0,6).map(product=>agentProductCard(product,dimensions)).join(''):'',boxes=[];
  if(scope.has('evidence'))boxes.push(`<div class="answer-box"><h3>可复核证据</h3><ul>${listItems(evidence,'本次没有可展示的企业证据。')}</ul></div>`);
  if(scope.has('warnings')&&warnings.length)boxes.push(`<div class="answer-box"><h3>风险与边界</h3><ul>${listItems(warnings,'')}</ul></div>`);
  if(scope.has('missing_data')&&(result.missing_data||[]).length)boxes.push(`<div class="answer-box"><h3>缺失数据</h3><ul>${listItems(result.missing_data,'')}</ul></div>`);
  if(scope.has('next_actions')&&(result.next_actions||[]).length)boxes.push(`<div class="answer-box"><h3>建议下一步</h3><ul>${listItems(result.next_actions,'')}</ul></div>`);
  $('#agentOutput').innerHTML=`<div class="agent-answer decision-report">${agentResultHeader(result,title)}<section class="recommendation-hero"><span>${label}</span><h3>${answer}</h3></section><div class="answer-metrics"><div class="answer-metric"><span>匹配商品</span><b>${result.matched_count??products.length}</b></div><div class="answer-metric"><span>当前展示</span><b>${result.displayed_count??products.length}</b></div>${type==='decision_report'?`<div class="answer-metric"><span>正式推荐</span><b>${decision.recommended_count??0}</b></div>`:''}<div class="answer-metric"><span>实际工具调用</span><b>${result.tool_call_count??0}</b></div></div>${topCards?`<div class="agent-product-grid">${topCards}</div>`:''}${scope.has('products')?agentProductTable(products,dimensions):''}${boxes.length?`<div class="answer-grid">${boxes.join('')}</div>`:''}${scope.has('tool_summary')?agentTraceBlock(result):''}<div class="provider-boundary">${esc(clean(result.provider_notice||'精确计算、筛选与审核闸门由后端负责。'))}</div></div>`;
}
async function askAgent(){const query=$('#agentQuery').value.trim();if(!query){toast('请先输入一个明确的分析问题。',true);return}const selected_product_ids=[...state.compare];const button=$('#agentButton');button.disabled=true;$('#agentOutput').innerHTML='<div class="thinking-state"><div class="thinking-orb"><svg><use href="#i-spark"/></svg></div><h2>正在理解目标并执行企业工具</h2><p>商品 ID、精确计算、租户权限和审核闸门全部由后端校验。</p></div>';try{const result=await api('/agent/ask',{method:'POST',body:JSON.stringify({query,session_id:state.agentSessionId,selected_product_ids})});state.agentSessionId=result.session_id||state.agentSessionId;state.lastAgentResult=result;renderAgentResult(result);await refreshDashboardOnly()}catch(error){$('#agentOutput').innerHTML=`<div class="thinking-state"><h2>分析未完成</h2><p>${esc(error.message)}</p></div>`;toast(error.message,true)}finally{button.disabled=false}}
async function refreshDashboardOnly(){try{state.dashboard=await api('/dashboard/overview');renderShell();renderOverview();renderCopilotSide()}catch(_){}}

function factRow(label,value,source='企业主档'){return `<div class="fact-row"><span>${esc(label)}</span><b>${esc(value||'未知')}</b><em>${esc(source)}</em></div>`}
function explanationCard(label,item={}){const drivers=Array.isArray(item.drivers)?item.drivers:[];return `<article class="explanation-card"><header><b>${esc(label)}</b><strong>${score(item.score)}</strong></header><ul>${drivers.map(driver=>`<li>${esc(driver)}</li>`).join('')||'<li>暂无足够证据。</li>'}</ul><p>${esc(item.formula||'由后端确定性规则计算。')}</p></article>`}
async function viewProduct(id,forceAnalyze=false){
  try{
    if(forceAnalyze){await api(`/products/${id}/analyze`,{method:'POST',body:'{}'});await refreshAll()}
    const [product,history]=await Promise.all([api(`/products/${id}`),api(`/products/${id}/history`)]),a=product.analysis||{},risks=a.risks||[],missing=a.missing_data||[],explanations=a.score_explanations||{},sourceUrl=safeUrl(product.url),lineage=product.field_lineage||{};
    const sourceFor=field=>lineage[field]?.source||lineage[field]||'企业主档';
    $('#drawerTitle').textContent=product.title;$('#drawerSubtitle').textContent=`${product.brand||'品牌待确认'} · ${product.category_path||'类目待确认'}`;
    $('#drawerContent').innerHTML=`<div class="detail-hero enterprise-detail">${thumb(product,'large')}<div><div class="detail-title-line"><h3>${esc(product.title)}</h3><span class="grade-badge ${gradeClass(a.recommendation_grade)}">${esc(a.recommendation_grade||'C')}</span></div><p>Ozon ID ${esc(product.external_product_id)} · 更新于 ${relativeTime(product.updated_at)}</p><div class="detail-badges">${riskBadge(a.risk_level)}${statusBadge(product.lifecycle_status)}${product.raw_payload?.demo_data?'<span class="pill teal">演示数据，不代表实时市场</span>':''}${sourceUrl?`<a class="source-link" href="${esc(sourceUrl)}" target="_blank" rel="noopener noreferrer">打开 Ozon 来源 ↗</a>`:''}</div></div></div>
      <div class="detail-metrics six"><div class="detail-metric"><span>推荐度</span><b>${score(a.recommendation_score)}</b></div><div class="detail-metric"><span>当前售价</span><b>${money(product.current_price)}</b></div><div class="detail-metric"><span>单件净利润</span><b>${money(a.net_profit)}</b></div><div class="detail-metric"><span>净利率</span><b>${percent(a.net_margin)}</b></div><div class="detail-metric"><span>ROI</span><b>${percent(a.roi)}</b></div><div class="detail-metric"><span>数据完整度</span><b>${a.evidence_completeness?.percent??a.data_completeness??0}%</b></div></div>
      <div class="detail-section"><div class="section-title-row"><h3>五维确定性评分</h3><span>算法 ${esc(a.algorithm_version||'待分析')}</span></div><div class="dimension-list">${dimensionRow('利润',a.profit_score,'#11a77a')}${dimensionRow('需求',a.demand_score,'#3c83ed')}${dimensionRow('竞争友好度',a.competition_score,'#d98d30')}${dimensionRow('合规',a.compliance_score,'#5e8dce')}${dimensionRow('风险安全',a.risk_score,'#775fda')}</div><div class="explanation-grid">${explanationCard('利润为什么高/低',explanations.profit)}${explanationCard('需求为什么高/低',explanations.demand)}${explanationCard('竞争为什么高/低',explanations.competition)}${explanationCard('合规为什么高/低',explanations.compliance)}${explanationCard('风险为什么高/低',explanations.risk)}</div></div>
      <div class="detail-section"><h3>商品事实与数据来源</h3><div class="fact-grid">${factRow('品牌',product.brand,sourceFor('brand'))}${factRow('类目',product.category_path,sourceFor('category_path'))}${factRow('Seller / 来源',product.seller_name,sourceFor('seller_name'))}${factRow('常规价',money(product.regular_price),sourceFor('regular_price'))}${factRow('竞品最低价',money(product.competitor_price_min),sourceFor('competitor_price_min'))}${factRow('竞品均价',money(product.competitor_price_avg),sourceFor('competitor_price_avg'))}${factRow('价格位置',product.price_position||'unknown','评估引擎')}${factRow('近30天销量',product.latest_30d_sales?String(product.latest_30d_sales):'未知',sourceFor('latest_30d_sales'))}${factRow('搜索量',product.search_volume?String(product.search_volume):'未知',sourceFor('search_volume'))}${factRow('评分 / 评论',product.rating?`${product.rating} / ${product.review_count}`:'未知',sourceFor('rating'))}${factRow('市场饱和度',product.market_saturation?`${product.market_saturation}/100`:'未知',sourceFor('market_saturation'))}${factRow('证书',product.certificates?.length?product.certificates.join('、'):'未知',sourceFor('certificates'))}</div></div>
      <div class="detail-section"><h3>风险与待补数据</h3><div class="risk-list">${risks.length||missing.length?risks.map(r=>`<div class="risk-item ${r.level==='high'?'high':''}"><b>${esc(r.code)}</b><br>${esc(r.message)}<br><span class="muted">建议：${esc(r.action)}</span></div>`).join('')+missing.map(x=>`<div class="risk-item"><b>${esc(dimensionNames[x.dimension]||x.dimension)}</b><br>${esc(x.missing)}</div>`).join(''):'<div class="muted">当前口径未发现新的风险或缺失项，但最终决策仍需人工审核。</div>'}</div></div>
      <div class="detail-section"><h3>历史快照（${history.length}）</h3><div class="table-scroll"><table class="history-table"><thead><tr><th>采集时间</th><th>价格</th><th>销量</th><th>评论</th><th>竞品</th></tr></thead><tbody>${history.slice(-8).reverse().map(row=>`<tr><td>${apiDate(row.captured_at).toLocaleString('zh-CN')}</td><td>${money(row.price)}</td><td>${row.sales_30d||'—'}</td><td>${row.review_count||'—'}</td><td>${row.competitor_count||'—'}</td></tr>`).join('')}</tbody></table></div></div>
      <div class="detail-actions"><button class="secondary-button" onclick="editProduct('${product.id}')">编辑主档</button><button class="secondary-button" onclick="viewProduct('${product.id}',true)">重新分析</button><button class="secondary-button" onclick="toggleCompare('${product.id}',true);toast('已加入对比中心。')">加入对比</button><button class="primary-button" onclick="openDecisionModal('${product.id}')">进入人工审核</button></div>`;openDrawer();
  }catch(error){toast(error.message,true)}
}
function dimensionRow(label,value,color){return `<div class="dimension-row"><span>${label}</span>${progress(value,color)}<b>${score(value)}</b></div>`}
function openDrawer(){$('#drawer').classList.remove('hidden');$('#drawer').setAttribute('aria-hidden','false');document.body.classList.add('no-scroll')}
function closeDrawer(){if(!$('#drawer'))return;$('#drawer').classList.add('hidden');$('#drawer').setAttribute('aria-hidden','true');if($('#editor').classList.contains('hidden')&&$('#decisionModal').classList.contains('hidden'))document.body.classList.remove('no-scroll')}

function form(){return $('#productForm')}function input(name){return form().elements[name]}
function formTab(name,button){document.querySelectorAll('.form-pane').forEach(node=>node.classList.toggle('active',node.dataset.formPane===name));document.querySelectorAll('.form-tabs button').forEach(node=>node.classList.toggle('active',node===button))}
function resetFormTabs(){const button=document.querySelector('.form-tabs button');formTab('identity',button)}
function newProduct(){state.editingId=null;state.editingRawPayload={};form().reset();input('external_product_id').disabled=false;input('platform_commission_rate').value='.18';input('target_margin_rate').value='.30';input('sales_source').value='not_provided';input('competitor_entries_json').value='[]';$('#formTitle').textContent='新建企业候选';resetFormTabs();openEditor()}
async function editProduct(id){try{const product=await api(`/products/${id}`);state.editingId=id;state.editingRawPayload=product.raw_payload||{};form().reset();input('external_product_id').disabled=true;Object.keys(product).forEach(key=>{if(input(key))input(key).value=product[key]??''});input('external_product_id').value=product.external_product_id;input('tag_text').value=(product.tags||[]).join(',');input('certificate_text').value=(product.certificates||[]).join(',');input('competitor_entries_json').value=JSON.stringify(product.visible_competitors||product.competitor_entries||[],null,2);input('abandon_reason').value=product.raw_payload?.abandonReason||'';$('#formTitle').textContent=`编辑：${product.title}`;resetFormTabs();closeDrawer();openEditor()}catch(error){toast(error.message,true)}}
function openEditor(){$('#editor').classList.remove('hidden');$('#editor').setAttribute('aria-hidden','false');document.body.classList.add('no-scroll')}
function closeEditor(){$('#editor').classList.add('hidden');$('#editor').setAttribute('aria-hidden','true');state.editingId=null;state.editingRawPayload={};if($('#drawer').classList.contains('hidden')&&$('#decisionModal').classList.contains('hidden'))document.body.classList.remove('no-scroll')}
form().addEventListener('submit',async event=>{event.preventDefault();const wasEditing=Boolean(state.editingId),editingId=state.editingId,editingRawPayload=state.editingRawPayload,data=Object.fromEntries(new FormData(form()));['current_price','regular_price','rating','review_count','latest_30d_sales','sales_growth_rate','search_volume','trend_score','competitor_count','competitor_price_min','competitor_price_avg','price_competition_score','market_saturation','procurement_cost','shipping_cost','fulfillment_cost','platform_fee','advertising_cost','warehousing_cost','tax_cost','return_loss_reserve','other_cost','platform_commission_rate','target_margin_rate'].forEach(key=>data[key]=Number(data[key]||0));data.tags=(data.tag_text||'').split(',').map(x=>x.trim()).filter(Boolean);data.certificates=(data.certificate_text||'').split(',').map(x=>x.trim()).filter(Boolean);delete data.tag_text;delete data.certificate_text;data.image_urls=data.main_image_url?[data.main_image_url]:[];try{data.competitor_entries=JSON.parse(data.competitor_entries_json||'[]');if(!Array.isArray(data.competitor_entries))throw new Error()}catch(_){toast('竞品 JSON 格式不正确。',true);return}delete data.competitor_entries_json;const abandonReason=data.abandon_reason||'';delete data.abandon_reason;data.raw_payload={...editingRawPayload,source:'enterprise_workbench',abandonReason};if(!wasEditing)data.field_lineage={entry:{source:'manual_enterprise_form',captured_at:new Date().toISOString()}};try{let product;if(wasEditing){delete data.external_product_id;delete data.field_lineage;product=await api(`/products/${editingId}`,{method:'PATCH',body:JSON.stringify(data)})}else{product=await api('/products',{method:'POST',body:JSON.stringify(data)})}await api(`/products/${product.id}/analyze`,{method:'POST',body:'{}'});closeEditor();toast(`${wasEditing?'已更新':'已创建'}商品主档，已生成新快照并完成五维分析。`);await refreshAll();viewProduct(product.id)}catch(error){toast(error.message,true)}});

async function seedDemo(){const active=document.activeElement,button=active instanceof HTMLButtonElement?active:null;if(button){button.disabled=true;button.textContent='正在建立演示组合…'}try{const result=await api('/demo/seed',{method:'POST',body:JSON.stringify({replace_demo:false})});toast(`已建立 ${result.created} 个演示候选。`);await refreshAll()}catch(error){toast(error.message,true)}finally{if(button){button.disabled=false;button.textContent='加载演示数据'}}}
function download(name,content,type='text/csv;charset=utf-8'){const blob=new Blob(['\ufeff',content],{type}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function csvCell(value){return `"${String(value??'').replace(/"/g,'""')}"`}
function exportProducts(){const head=['商品ID','标题','品牌','类目','售价RUB','净利率','30天销量','动态推荐度','风险','完整度','生命周期'],rows=state.products.map(p=>[p.external_product_id,p.title,p.brand,p.category_path,p.current_price,p.current_margin_rate,p.latest_30d_sales,p.analysis?.recommendation_score,p.analysis?.risk_level,p.analysis?.evidence_completeness?.percent,p.lifecycle_status]);download(`ozon-候选商品-${new Date().toISOString().slice(0,10)}.csv`,[head,...rows].map(row=>row.map(csvCell).join(',')).join('\n'))}
function exportPortfolio(){const m=state.dashboard?.metrics||{},lines=[['OZON 商机智选经营简报',new Date().toLocaleString('zh-CN')],['候选商品',m.total_products||0],['平均动态推荐度',m.average_score??'—'],['待人工审核',m.pending_reviews||0],['高风险商品',m.high_risk_products||0],['已验证月利润潜力',m.verified_monthly_profit_potential||0],[],['商品','推荐度','净利率','风险','完整度'],...state.products.map(p=>[p.title,p.analysis?.recommendation_score??'—',p.current_margin_rate,p.analysis?.risk_level||'未分析',p.analysis?.evidence_completeness?.percent??0])];download(`ozon-经营简报-${new Date().toISOString().slice(0,10)}.csv`,lines.map(row=>row.map(csvCell).join(',')).join('\n'))}

async function boot(){navigate(location.hash.slice(1)||'overview',false);await refreshAll()}
boot();
